version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: primez-pinchflat_server_1
      APP_PORT: 8945
    
  server:
    image: ghcr.io/kieraneglin/pinchflat:latest
    init: true
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - LOG_LEVEL=warning
      - TZ=${TZ:-UTC}

    volumes:
      - ${APP_DATA_DIR}/appdata:/config
      - ${UMBREL_ROOT}/data/storage/downloads/youtube:/downloads
      
