services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: primez-dozzle_server_1
      APP_PORT: 8080
    
  server:
    image: amir20/dozzle:latest
    init: true
    restart: on-failure
    stop_grace_period: 10s
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
      
