version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: primez-dozzle_dozzle_server_1
      APP_PORT: 8080
    
  dozzle_server:
    image: amir20/dozzle:latest
    user: "1000:1000"
    init: true
    security_opt:
      - no-new-privileges:true
    restart: on-failure
    stop_grace_period: 30s
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
      
